### ISSUE TITLE
Preparation for v0.8

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/AstroNvim#391]
This is just a placeholder for keeping up with changes that are coming with Neovim v0.8.

## TODO

- [x] `resolved_capabilities` deprecated (https://github.com/neovim/neovim/pull/17814)
- [x] `nvim_cmd` API addition (https://github.com/neovim/neovim/pull/18366)
- [x] Use `feline` to set up `winbar` for breadcrumbs in active window and filename for inactive window (https://github.com/neovim/neovim/pull/18562)
- [x] Investigate `cmdheight = 0` (https://github.com/neovim/neovim/pull/16251)
- [x] Remove deprecated `filetype.lua` options (https://github.com/neovim/neovim/pull/19216)
- [x] https://github.com/neovim/neovim/pull/19238

**Comment by mehalter** [comment]
The latest commit on the [`neovim-0.8` branch](https://github.com/AstroNvim/AstroNvim/tree/neovim-0.8) adds some winbar goodies

![2022-05-25_17:23:22_screenshot](https://user-images.githubusercontent.com/1591837/170369748-d71dea0a-7205-4c5c-a061-06ac0fb09a23.png)

**Comment by mehalter** [comment]
Updated the `winbar` commit to make it look a lot nicer. Anyone using the `neovim-0.8` branch should do a `git pull --rebase` to get the changes :)
![2022-05-26_12:12:21_screenshot](https://user-images.githubusercontent.com/1591837/170529170-e3fd167f-5b16-4839-ab1c-ad7200a257a8.png)

**Comment by mehalter** [comment]
Added `cmdheight=0` as default
![2022-06-14_08:15:10_screenshot](https://user-images.githubusercontent.com/1591837/173577236-f4af188c-6c9d-4384-b106-53bfc6308b17.png)

**Comment by flamendless** [comment]
Im looking for breadcrumbs functionality, my previous config has it but since latest config uses a new statusline my old config for it will be harder to setup. Can this be used now? how?

**Comment by mehalter** [comment]
@flamendless Yeah it should be happening automatically out of the box in the winbar as shown in the screenshot with feline.

**Comment by mehalter** [comment]
With this new migration to Heirline we are also able to disable the WinBar on a per buffer basis. So now sidebars don't have a blank line at the top 
![2022-06-28_10:36:08_screenshot](https://user-images.githubusercontent.com/1591837/176207459-be400d14-1f7d-4a14-a30e-ee12b51324f3.png)

**Comment by mehalter** [comment]
Since all of the current preparation to Neovim 0.8 is finished so far and there is an open pull request/branch also tracking this, I am going to go ahead and close this issue in favor of using the PR #715 for future discussion

**Comment by cmndrsp0ck** [comment]
how do i get the heirline to show file name and not just filetype?
