### ISSUE TITLE
Move to Heirline

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/AstroNvim#686]
Investigate the migration from Feline to [Heirline](https://github.com/rebelot/heirline.nvim) for the statusbar.

This should be a relatively simple migration and leave the user configuration nearly identical since the setup functions are quite similar. But it seems to be much better thought out and organized than Feline when it comes to some customizations as well as the theming/colorscheme integration.

This will be a breaking change so if it happens, it will coincide with the AstroNvim 2.0.0 release (when Neovim v0.8 becomes stable and supported)

This will allow a few things that we can't do currently in Feline:

- Better theming support (less hacky solution than what we have currently
- Per-window winbar (neovim 0.8 feature) so we can disable winbar for stuff like the sidebars (symbol outline/tree)
- Maximum width for status bar components, mainly looking to limit the size of language servers which currently can span the entire statusline before shortening

### TODO

- [x] Make statusline self contained (define all our own providers)
- [x] Move to Heirline
- [x] Set up max width for LSP sources
- [x] Add spacer character feature
- [x] Add configurable component backgrounds/foregrounds

**Comment by mehalter** [comment]
I'm going to go ahead and close this since it's implemented and waiting until the v2.0.0 release
